### ISSUE TITLE
Probleme lors du lancement Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor

### ISSUE THREAD

**Issue by tsubeyy** [Litarvan/OpenAuth#10]
Bonjour jetais entrais de coder mon launcher personnel et j'ai eu cette
erreur impossible de lancer le jeu voice le probleme
[18:12:49] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:12:49] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[18:12:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:12:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:12:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.getConstructor0(Class.java:3075)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.newInstance(Class.java:412)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:108)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[18:12:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 8 more

et voila le code `package com.madjido.fr.launcher;

import java.io.File;
import java.io.IOException;

import fr.theshark34.openauth.AuthPoints;
import fr.theshark34.openauth.AuthenticationException;
import fr.theshark34.openauth.Authenticator;
import fr.theshark34.openauth.model.AuthAgent;
import fr.theshark34.openauth.model.response.AuthResponse;
import fr.theshark34.openlauncherlib.launcher.AuthInfos;
import fr.theshark34.openlauncherlib.launcher.GameFolder;
import fr.theshark34.openlauncherlib.launcher.GameInfos;
import fr.theshark34.openlauncherlib.launcher.GameLauncher;
import fr.theshark34.openlauncherlib.launcher.GameTweak;
import fr.theshark34.openlauncherlib.launcher.GameType;
import fr.theshark34.openlauncherlib.launcher.GameVersion;
import fr.theshark34.supdate.BarAPI;
import fr.theshark34.supdate.SUpdate;
import fr.theshark34.supdate.application.integrated.FileDeleter;
import fr.theshark34.swinger.Swinger;
public class Launcher {

	public static final GameVersion SC_VERSION = new GameVersion("1.7.10", GameType.V1_7_10);
	public static final GameInfos SC_INFOS = new GameInfos("Lunaria", SC_VERSION ,true ,new GameTweak[] {GameTweak.FORGE});
	public static final File SC_DIR = SC_INFOS.getGameDir();
	
	private static AuthInfos authInfos;
	private static Thread updateThread;
	
	public static void auth(String username, String password) throws AuthenticationException{
		Authenticator authentificator = new Authenticator(Authenticator.MOJANG_AUTH_URL, AuthPoints.NORMAL_AUTH_POINTS);
		AuthResponse response = authentificator.authenticate(AuthAgent.MINECRAFT, username, password, "");
		authInfos = new AuthInfos(response.getSelectedProfile().getName(), response.getAccessToken(), response.getSelectedProfile().getId());
	}
	
	public static void update() throws Exception {
		SUpdate su = new SUpdate("https://launcherpanel.000webhostapp.com/", SC_DIR);
		su.addApplication(new FileDeleter());
		
		updateThread = new Thread() {
			private int val;
			private int max;
			@Override
			public void run() {
				while(!this.isInterrupted()) {
					if(BarAPI.getNumberOfFileToDownload() == 0){
						LauncherFrame.getInstance().getLauncherPanel().setInfoText("Verification des fichers...");
						continue;
					}
					val = (int) (BarAPI.getNumberOfTotalDownloadedBytes() / 1000);
					max = (int) (BarAPI.getNumberOfTotalBytesToDownload() / 1000);
					
					
					
					LauncherFrame.getInstance().getLauncherPanel().getProgressBar().setMaximum(max);
                    LauncherFrame.getInstance().getLauncherPanel().getProgressBar().setValue(val);
                    
                    LauncherFrame.getInstance().getLauncherPanel().setInfoText("Telechargement des fichiers... " 
                    + BarAPI.getNumberOfDownloadedFiles() + "/" + BarAPI.getNumberOfFileToDownload() +
                    Swinger.percentage(val, max) + "%");
					
				}
			}
		};
		updateThread.start();
		
		su.start();
		
		updateThread.interrupt();
	}
	
	public static void launch() throws IOException {
		GameLauncher gameLauncher = new GameLauncher(SC_INFOS,GameFolder.BASIC,authInfos);
		Process p = gameLauncher.launch();
		try {
			Thread.sleep(5000L);
		} catch (InterruptedException e) {
			
		}
		LauncherFrame.getInstance().setVisible(false);
		try {
			p.waitFor();;
		} catch (InterruptedException e) {
			
		}
		System.exit(0);
	}
	
	public static void interruptThread() {
		updateThread.interrupt();
	}
	
}
`
Merci de repondre.

**Comment by Litarvan** [comment]
Salut, ce n'est pas lié à OpenAuth, il te manque des librairies dans le dossier du jeu, je te laisse gérer ça sur le Discord de support
